- prisma/migrations/20231011193501_token_uuid/migration.sql
- prisma/schema.prisma
- src/lib/components/Backdrop.svelte
- src/lib/components/admin/InviteUser.svelte
- src/lib/components/admin/SettingsForm/index.svelte
- src/lib/components/modals/InviteUserModal.svelte
- src/lib/components/wishlists/ItemForm.svelte
- src/lib/server/invite-user.ts
- src/routes/admin/groups/[groupId]/members/+page.server.ts
- src/routes/admin/groups/[groupId]/members/+page.svelte
- src/routes/admin/users/+page.server.ts
- src/routes/reset-password/+page.server.ts
- src/routes/reset-password/+page.svelte
- src/routes/signup/+page.server.ts
> Group invite fixes

- src/lib/components/wishlists/ItemForm.svelte
- src/routes/api/product/+server.ts
Extract the url from item_url string. Also retry if we get a captcha. This fix is mainly for Amazon being Amazon
> extract url from item url string and retry if captcha

- src/routes/wishlists/[username]/+page.svelte
> sort unclaimed items to the top

- src/routes/+page.server.ts
- src/routes/+page.svelte
- src/routes/wishlists/[username]/+page.server.ts
- src/routes/wishlists/[username]/+page.svelte
> hash items with group id

- src/lib/components/wishlists/ItemForm.svelte
Only fetches an item the first time the url is filled in and add a refresh button to refresh the item if you change the url or want to refresh it later.
Fixes #124
> Only fetch item once

- package.json
- pnpm-lock.yaml
- prisma/migrations/20240825030505_add_display_order/migration.sql
- prisma/schema.prisma
- src/lib/api/items.ts
- src/lib/components/wishlists/ItemCard/ItemCard.svelte
- src/lib/components/wishlists/ItemCard/ReorderButtons.svelte
- src/lib/components/wishlists/ItemForm.svelte
- src/lib/components/wishlists/chips/ReorderChip.svelte
- src/lib/schema.ts
- src/lib/server/api-common.ts
- src/routes/api/items/+server.ts
- src/routes/api/items/[itemId]/+server.ts
- src/routes/wishlists/[username]/+page.server.ts
- src/routes/wishlists/[username]/+page.svelte
- src/routes/wishlists/[username]/events/+server.ts
- src/routes/wishlists/[username]/new/+page.svelte
Adds the ability to re-order items using drag-and-drop or arrows. The item order set by the wishlist user will be the default order shown
> Add Item ordering

- src/lib/components/wishlists/ItemCard/ApprovalButtons.svelte
- src/lib/components/wishlists/ItemCard/ItemCard.svelte
- src/lib/components/wishlists/ItemDrawer.svelte
> More item drawer fixes

- src/lib/components/CurrencyInput.svelte
- src/lib/components/wishlists/ItemForm.svelte
- src/lib/price-formatter.ts
When no price is entered it should not save as $0 and instead should save as null
> Fix for prices being 0 when it should be null

- src/lib/components/admin/Groups.svelte
- src/lib/components/admin/InviteUser.svelte
- src/lib/server/email.ts
- src/lib/server/invite-user.ts
- src/routes/admin/groups/[groupId]/members/+page.svelte
- src/routes/setup-wizard/step/[step]/InviteUsersStep.svelte
Fixes #153
Fixes issues introduced by #106 relating to logic and reactivity with the invite users modal
> fix invitions and add better error handling

- src/ambient.d.ts
- src/lib/components/PasswordInput.svelte
- src/lib/components/admin/SettingsForm/BaseSetting.svelte
- src/lib/components/admin/SettingsForm/Claims.svelte
- src/lib/components/admin/SettingsForm/ListMode.svelte
- src/lib/components/admin/SettingsForm/PublicSignup.svelte
- src/lib/components/admin/SettingsForm/SMTP.svelte
- src/lib/components/admin/SettingsForm/Security.svelte
- src/lib/components/admin/SettingsForm/Suggestions.svelte
- src/lib/components/admin/SettingsForm/index.svelte
- src/lib/server/config.ts
- src/lib/server/email.ts
- src/lib/validations.ts
- src/lib/zxcvbn.ts
- src/routes/account/+page.server.ts
- src/routes/admin/settings/+page.server.ts
- src/routes/reset-password/+page.server.ts
- src/routes/signup/+page.server.ts
> Allow minimum password strength to be configurable globally

- src/ambient.d.ts
- src/lib/components/admin/SettingsForm/DefaultGroup.svelte
- src/lib/components/admin/SettingsForm/index.svelte
- src/lib/server/config.ts
- src/lib/validations.ts
- src/routes/admin/groups/[groupId]/members/+page.svelte
- src/routes/admin/settings/+page.server.ts
- src/routes/admin/settings/+page.svelte
- src/routes/setup-wizard/step/[step]/GlobalSettingsStep.svelte
- src/routes/signup/+page.server.ts
> Default group

- src/lib/server/image-util.ts
Fixes https://github.com/cmintey/wishlist/issues/196
> Appropriately apply rotation to uploaded images before conversion

- src/routes/api/product/+server.ts
> replace url if its the same as the image

- src/routes/reset-password/+page.svelte
> Fix password reset form

- src/i18n/en.json
- src/lib/components/wishlists/ItemCard/ItemCard.svelte
- src/routes/lists/[id]/+page.svelte
- src/routes/lists/[id]/create-item/+page.server.ts
- Fix for allowing logged in users to create an item on a registry when suggestions are enabled.
- Hides the create item button on registries when user is anonymous
- Shows who added an item when a user is anonymous
Closes #252 
Closes #251
> Fix create registry item

- src/routes/api/items/+server.ts
Foreign key constraint. Need to delete item claims before the item
Fixes #254
> fix: Unable to clear claimed items

- prisma/migrations/20250329193312_item_claim_cascade_delete/migration.sql
- prisma/schema.prisma
- src/routes/api/lists/[listId]/items/[itemId]/+server.ts
> delete item claims before removing item

- package.json
- pnpm-lock.yaml
- src/hooks.server.ts
- src/lib/components/wishlists/ItemForm.svelte
- src/lib/server/email.ts
- src/lib/server/events/sse.ts
- src/lib/server/image-util.ts
- src/lib/server/logger.ts
- src/lib/server/openid.ts
- src/routes/account/+page.server.ts
- src/routes/api/claims/[claimId]/+server.ts
- src/routes/api/items/+server.ts
- src/routes/api/lists/[listId]/items/+server.ts
- src/routes/api/lists/[listId]/items/[itemId]/+server.ts
- src/routes/api/lists/[listId]/items/[itemId]/claims/+server.ts
- src/routes/lists/[id]/manage/+page.server.ts
- src/routes/lists/create/+page.server.ts
- src/routes/login/+page.server.ts
- src/routes/login/oidc/callback/+server.ts
Adds pinojs as a logger instead of using console.log
> Add a real logger

- .gitignore
- .npmrc
- package.json
- pnpm-lock.yaml
- src/ambient.d.ts
- src/app.html
- src/routes/+layout.svelte
- svelte.config.js
- tsconfig.json
Update Vite PWA library and use the virtual methods to dynamically add the webmanifest link to head and register service worker
> Update Vite PWA

- .env.example
- README.md
- package.json
- pnpm-lock.yaml
- src/lib/server/logger.ts
- src/lib/server/openid.ts
- src/routes/login/oidc/callback/+server.ts
To enable debug logging, set `LOG_LEVEL=debug` in the environment variables
> Add debug logging for oidc flow

- README.md
> Add helm chart to readme

- src/lib/components/modals/ClaimItemModal.svelte
- src/lib/components/toasts.ts
- src/lib/components/wishlists/ItemCard/ItemCard.svelte
- src/routes/api/lists/[listId]/items/[itemId]/claims/+server.ts
> Fix public claims

- package.json
- pnpm-lock.yaml
- src/i18n/en.json
- src/lib/components/wishlists/ItemForm.svelte
- src/routes/lists/[id]/create-item/+page.svelte
> Add "create and stay" button on item form

- src/lib/components/wishlists/ItemCard/ItemCard.svelte
- src/lib/components/wishlists/chips/BaseChip.svelte
- src/lib/components/wishlists/chips/ClaimFilter.svelte
- src/lib/server/list.ts
- src/lib/server/sort-filter-util.ts
- src/routes/lists/[id]/+page.svelte
> Fix claim filter on list page

- src/lib/server/image-util.ts
- src/lib/server/validations.ts
- src/routes/items/[itemId]/edit/+page.server.ts
- src/routes/lists/[id]/create-item/+page.server.ts
Download the image from the given url when creating or editing an item. The image is saved as a webp on the server and resize it to make it more appropriate for the application.
Closes #228
> Download item images

- src/lib/components/wishlists/ItemForm.svelte
- src/lib/server/shopping/index.ts
- src/routes/api/product/+server.ts
> fix: Send product encoded product url to product API

- src/routes/login/oidc/callback/+server.ts
> fix: remove duplicate create membership step for OIDC new user

- prisma/migrations/20250729023729_list_description/migration.sql
- prisma/schema.prisma
- src/i18n/en.json
- src/lib/components/MarkdownEditor.svelte
- src/lib/components/wishlists/ItemForm.svelte
- src/lib/components/wishlists/ManageListForm.svelte
- src/lib/server/list.ts
- src/lib/server/validations.ts
- src/routes/+page.server.ts
- src/routes/lists/[id]/+page.svelte
- src/routes/lists/[id]/manage/+page.server.ts
- src/routes/lists/create/+page.server.ts
Allows adding an optional description on a list. This can be used for things like adding your clothes sizes or preferences.
Closes #341
Closes https://github.com/cmintey/wishlist/discussions/316
> Add a description to lists

- src/lib/server/validations.ts
> Fix default list creation setting not persisting

- src/lib/server/image-util.ts
- src/routes/account/+page.svelte
- src/routes/items/[itemId]/edit/+page.svelte
- src/routes/lists/[id]/create-item/+page.svelte
Handle image processing errors more gracefully with an error toast
Fixes #351
> Fix failed image processing crashes container

- src/lib/server/config.ts
> Rework configuration creation and fetching

- .gitignore
- .npmrc
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- vite.config.ts
> Set supported architectures for sharp
